/**
 * Supabase-generated TypeScript types
 *
 * This file is auto-generated by Supabase CLI.
 * To regenerate, run:
 *   npx supabase gen types typescript --local > src/lib/supabase-database.types.ts
 *
 * Or for remote projects:
 *   npx supabase gen types typescript --project-id "$PROJECT_REF" > src/lib/supabase-database.types.ts
 *
 * NOTE: This is a placeholder. You need to run the Supabase CLI command above
 * to generate the actual types from your database schema.
 */

export type Json =
	| string
	| number
	| boolean
	| null
	| { [key: string]: Json | undefined }
	| Json[];

export interface Database {
	public: {
		Tables: {
			advertisements: {
				Row: {
					id: string;
					user_id: string;
					website_url: string;
					name: string;
					description: string;
					logo_url: string | null;
					status: "pending" | "active" | "rejected" | "expired";
					approved: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					website_url: string;
					name: string;
					description: string;
					logo_url?: string | null;
					status?: "pending" | "active" | "rejected" | "expired";
					approved?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					website_url?: string;
					name?: string;
					description?: string;
					logo_url?: string | null;
					status?: "pending" | "active" | "rejected" | "expired";
					approved?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			mind_maps: {
				Row: {
					id: string;
					user_id: string;
					title: string;
					description: string | null;
					first_prompt: string;
					graph_data: Json;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					title: string;
					description?: string | null;
					first_prompt: string;
					graph_data: Json;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					title?: string;
					description?: string | null;
					first_prompt?: string;
					graph_data?: Json;
					created_at?: string;
					updated_at?: string;
				};
			};
			chat_messages: {
				Row: {
					id: string;
					mind_map_id: string;
					user_id: string;
					role: "user" | "ai";
					content: string;
					map_data?: Json | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					mind_map_id: string;
					user_id: string;
					role: "user" | "ai";
					content: string;
					map_data?: Json | null;
					created_at?: string;
				};
				Update: {
					id?: string;
					mind_map_id?: string;
					user_id?: string;
					role?: "user" | "ai";
					content?: string;
					map_data?: Json | null;
					created_at?: string;
				};
			};
			user_subscriptions: {
				Row: {
					id: string;
					user_id: string;
					tier: string;
					dodo_customer_id: string | null;
					dodo_subscription_id: string | null;
					current_period_start: string | null;
					current_period_end: string | null;
					cancel_at_period_end: boolean;
					cancelled_at: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					tier: string;
					dodo_customer_id?: string | null;
					dodo_subscription_id?: string | null;
					current_period_start?: string | null;
					current_period_end?: string | null;
					cancel_at_period_end?: boolean;
					cancelled_at?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					tier?: string;
					dodo_customer_id?: string | null;
					dodo_subscription_id?: string | null;
					current_period_start?: string | null;
					current_period_end?: string | null;
					cancel_at_period_end?: boolean;
					cancelled_at?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			user_credits: {
				Row: {
					id: string;
					user_id: string;
					credits: number;
					monthly_credits_remaining: number;
					monthly_credits_used: number;
					last_daily_credit_claimed_at: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					credits: number;
					monthly_credits_remaining: number;
					monthly_credits_used?: number;
					last_daily_credit_claimed_at?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					credits?: number;
					monthly_credits_remaining?: number;
					monthly_credits_used?: number;
					last_daily_credit_claimed_at?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			share_links: {
				Row: {
					id: string;
					mind_map_id: string;
					user_id: string;
					share_token: string;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					mind_map_id: string;
					user_id: string;
					share_token: string;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					mind_map_id?: string;
					user_id?: string;
					share_token?: string;
					created_at?: string;
					updated_at?: string;
				};
			};
		};
	};
}
