/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1HelloRouteImport } from './routes/v1/hello'
import { Route as ShareShareTokenRouteImport } from './routes/share/$shareToken'
import { Route as authProjectsRouteRouteImport } from './routes/(auth)/projects/route'
import { Route as authAccountRouteRouteImport } from './routes/(auth)/account/route'
import { Route as V1DodoSubscriptionWebhookRouteImport } from './routes/v1/dodo/subscription-webhook'
import { Route as authProjectProjectIdRouteImport } from './routes/(auth)/project/$projectId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1HelloRoute = V1HelloRouteImport.update({
  id: '/v1/hello',
  path: '/v1/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const authProjectsRouteRoute = authProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => authRouteRoute,
} as any)
const authAccountRouteRoute = authAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => authRouteRoute,
} as any)
const V1DodoSubscriptionWebhookRoute =
  V1DodoSubscriptionWebhookRouteImport.update({
    id: '/v1/dodo/subscription-webhook',
    path: '/v1/dodo/subscription-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const authProjectProjectIdRoute = authProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof authAccountRouteRoute
  '/projects': typeof authProjectsRouteRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/v1/hello': typeof V1HelloRoute
  '/project/$projectId': typeof authProjectProjectIdRoute
  '/v1/dodo/subscription-webhook': typeof V1DodoSubscriptionWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof authAccountRouteRoute
  '/projects': typeof authProjectsRouteRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/v1/hello': typeof V1HelloRoute
  '/project/$projectId': typeof authProjectProjectIdRoute
  '/v1/dodo/subscription-webhook': typeof V1DodoSubscriptionWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/(auth)/account': typeof authAccountRouteRoute
  '/(auth)/projects': typeof authProjectsRouteRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/v1/hello': typeof V1HelloRoute
  '/(auth)/project/$projectId': typeof authProjectProjectIdRoute
  '/v1/dodo/subscription-webhook': typeof V1DodoSubscriptionWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/projects'
    | '/share/$shareToken'
    | '/v1/hello'
    | '/project/$projectId'
    | '/v1/dodo/subscription-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/projects'
    | '/share/$shareToken'
    | '/v1/hello'
    | '/project/$projectId'
    | '/v1/dodo/subscription-webhook'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/privacy'
    | '/terms'
    | '/(auth)/account'
    | '/(auth)/projects'
    | '/share/$shareToken'
    | '/v1/hello'
    | '/(auth)/project/$projectId'
    | '/v1/dodo/subscription-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
  V1HelloRoute: typeof V1HelloRoute
  V1DodoSubscriptionWebhookRoute: typeof V1DodoSubscriptionWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/hello': {
      id: '/v1/hello'
      path: '/v1/hello'
      fullPath: '/v1/hello'
      preLoaderRoute: typeof V1HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/projects': {
      id: '/(auth)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof authProjectsRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/account': {
      id: '/(auth)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authAccountRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/v1/dodo/subscription-webhook': {
      id: '/v1/dodo/subscription-webhook'
      path: '/v1/dodo/subscription-webhook'
      fullPath: '/v1/dodo/subscription-webhook'
      preLoaderRoute: typeof V1DodoSubscriptionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/project/$projectId': {
      id: '/(auth)/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof authProjectProjectIdRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAccountRouteRoute: typeof authAccountRouteRoute
  authProjectsRouteRoute: typeof authProjectsRouteRoute
  authProjectProjectIdRoute: typeof authProjectProjectIdRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAccountRouteRoute: authAccountRouteRoute,
  authProjectsRouteRoute: authProjectsRouteRoute,
  authProjectProjectIdRoute: authProjectProjectIdRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
  V1HelloRoute: V1HelloRoute,
  V1DodoSubscriptionWebhookRoute: V1DodoSubscriptionWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
